//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mixing.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MixingEntities : DbContext
    {
        public MixingEntities()
            : base("name=MixingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mx_Element> mx_Element { get; set; }
        public virtual DbSet<mx_ElementGroup> mx_ElementGroup { get; set; }
        public virtual DbSet<mx_Formular> mx_Formular { get; set; }
        public virtual DbSet<mx_FormularDetail> mx_FormularDetail { get; set; }
        public virtual DbSet<mx_Object> mx_Object { get; set; }
        public virtual DbSet<mx_Setting> mx_Setting { get; set; }
        public virtual DbSet<mx_Substance> mx_Substance { get; set; }
        public virtual DbSet<mx_SubstanceDetail> mx_SubstanceDetail { get; set; }
        public virtual DbSet<mx_SubstanceGroup> mx_SubstanceGroup { get; set; }
        public virtual DbSet<mx_SubstanceUsedDefault> mx_SubstanceUsedDefault { get; set; }
        public virtual DbSet<mx_WebEmbedded> mx_WebEmbedded { get; set; }
    }
}
