//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mixing.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mx_FormularDetail
    {
        public int ID { get; set; }
        public Nullable<int> Formular_Ref { get; set; }
        public Nullable<int> Element_Ref { get; set; }
        public Nullable<int> TargetValue { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public string Unit { get; set; }
    
        public virtual mx_Element mx_Element { get; set; }
        public virtual mx_Formular mx_Formular { get; set; }
    }
}
