//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mixing.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mx_Substance
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public Nullable<int> SubstanceGroup_Ref { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string AdUrl { get; set; }
        public string InfoNote { get; set; }
        public string WarningNote { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
