//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mixing.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mx_SubstanceDetail
    {
        public int ID { get; set; }
        public Nullable<int> Substance_Ref { get; set; }
        public Nullable<int> Element_Ref { get; set; }
        public Nullable<int> Object_Ref { get; set; }
        public Nullable<double> NutritiveValue { get; set; }
        public string Unit { get; set; }
        public Nullable<bool> IsObjectDependence { get; set; }
    
        public virtual mx_Substance mx_Substance { get; set; }
        public virtual mx_Element mx_Element { get; set; }
    }
}
