//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mixing.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mx_SubstanceUsedDefault
    {
        public int ID { get; set; }
        public Nullable<int> Object_Ref { get; set; }
        public Nullable<int> Substance_Ref { get; set; }
        public string Description { get; set; }
    }
}
