//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mixing.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mx_WebEmbedded
    {
        public int ID { get; set; }
        public string DomainName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.DateTime> LimitDate { get; set; }
        public Nullable<int> CountCalculator { get; set; }
        public Nullable<int> LimitCalculator { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
